name: Docker Image run testing

on:
  push:
    branches: [ "main" , "workflow"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my_image
    - name: Run the image
      run: docker run  --name build -d my_image && docker exec -i build bash scripts/build.sh



