name: MainAction
on:
    push
jobs:
    job1:
        name: the only job
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout current repo
                uses: actions/checkout@v3
            -
                name: Use the provided Dockerfile to build an image
                run: docker build . --file Dockerfile --tag my_image
            -
                name: Run the image
                run: docker run  --name build my_image
            -
                name: list current dir
                run: ls -la
            -
                name: run tester
                run: ./scripts/test.sh
                
